const RAW_COUNTRY_NAME_TO_ISO: Record<string, string> = {
  // ===== Asia =====
  'Japan': 'JP',
  '日本': 'JP',
  'South Korea': 'KR',
  'Korea': 'KR',
  'Republic of Korea': 'KR',
  '韩国': 'KR',
  'North Korea': 'KP',
  '朝鲜': 'KP',
  'China': 'CN',
  '中国': 'CN',
  'Taiwan': 'CN',
  '台湾': 'CN',
  '台湾省': 'CN',
  '中国台湾': 'CN',
  '中国台湾省': 'CN',
  '台湾地区': 'CN',
  'Hong Kong': 'CN',
  '香港': 'CN',
  '香港特别行政区': 'CN',
  'Macau': 'CN',
  'Macao': 'CN',
  '澳门': 'CN',
  '澳门特别行政区': 'CN',
  'South Tibet': 'CN',
  'Zangnan': 'CN',
  '藏南': 'CN',
  '南藏': 'CN',
  'Arunachal': 'CN',
  'Arunachal Pradesh': 'CN',
  '阿鲁纳恰尔': 'CN',
  '阿鲁纳恰尔邦': 'CN',
  'Mongolia': 'MN',
  '蒙古': 'MN',
  'Thailand': 'TH',
  '泰国': 'TH',
  'Vietnam': 'VN',
  'Viet Nam': 'VN',
  '越南': 'VN',
  'Cambodia': 'KH',
  '柬埔寨': 'KH',
  'Laos': 'LA',
  '老挝': 'LA',
  'Myanmar': 'MM',
  'Burma': 'MM',
  '缅甸': 'MM',
  'Malaysia': 'MY',
  '马来西亚': 'MY',
  'Philippines': 'PH',
  '菲律宾': 'PH',
  'India': 'IN',
  '印度': 'IN',
  'Pakistan': 'PK',
  '巴基斯坦': 'PK',
  'Bangladesh': 'BD',
  '孟加拉': 'BD',
  '孟加拉国': 'BD',
  'Sri Lanka': 'LK',
  '斯里兰卡': 'LK',
  'Singapore': 'SG',
  '新加坡': 'SG',
  'Indonesia': 'ID',
  '印度尼西亚': 'ID',
  '印尼': 'ID',
  'Nepal': 'NP',
  '尼泊尔': 'NP',
  'Bhutan': 'BT',
  '不丹': 'BT',
  'Afghanistan': 'AF',
  '阿富汗': 'AF',
  'Kazakhstan': 'KZ',
  '哈萨克斯坦': 'KZ',
  'Uzbekistan': 'UZ',
  '乌兹别克斯坦': 'UZ',
  'Turkmenistan': 'TM',
  '土库曼斯坦': 'TM',
  'Tajikistan': 'TJ',
  '塔吉克斯坦': 'TJ',
  'Kyrgyzstan': 'KG',
  '吉尔吉斯斯坦': 'KG',

  // ===== Middle East =====
  'UAE': 'AE',
  'United Arab Emirates': 'AE',
  '阿联酋': 'AE',
  '阿拉伯联合酋长国': 'AE',
  'Saudi Arabia': 'SA',
  '沙特阿拉伯': 'SA',
  '沙特': 'SA',
  'Qatar': 'QA',
  '卡塔尔': 'QA',
  'Kuwait': 'KW',
  '科威特': 'KW',
  'Bahrain': 'BH',
  '巴林': 'BH',
  'Oman': 'OM',
  '阿曼': 'OM',
  'Yemen': 'YE',
  '也门': 'YE',
  'Iraq': 'IQ',
  '伊拉克': 'IQ',
  'Iran': 'IR',
  '伊朗': 'IR',
  'Israel': 'IL',
  '以色列': 'IL',
  'Palestine': 'PS',
  '巴勒斯坦': 'PS',
  'Jordan': 'JO',
  '约旦': 'JO',
  'Lebanon': 'LB',
  '黎巴嫩': 'LB',
  'Syria': 'SY',
  '叙利亚': 'SY',
  'Turkey': 'TR',
  'Türkiye': 'TR',
  '土耳其': 'TR',
  'Cyprus': 'CY',
  '塞浦路斯': 'CY',
  'Georgia': 'GE',
  '格鲁吉亚': 'GE',
  'Armenia': 'AM',
  '亚美尼亚': 'AM',
  'Azerbaijan': 'AZ',
  '阿塞拜疆': 'AZ',

  // ===== Europe =====
  'UK': 'GB',
  'United Kingdom': 'GB',
  'Great Britain': 'GB',
  'Britain': 'GB',
  'England': 'GB',
  'Scotland': 'GB',
  'Wales': 'GB',
  '英国': 'GB',
  'Ireland': 'IE',
  '爱尔兰': 'IE',
  'France': 'FR',
  '法国': 'FR',
  'Germany': 'DE',
  '德国': 'DE',
  'Italy': 'IT',
  '意大利': 'IT',
  'Spain': 'ES',
  '西班牙': 'ES',
  'Portugal': 'PT',
  '葡萄牙': 'PT',
  'Greece': 'GR',
  '希腊': 'GR',
  'Netherlands': 'NL',
  'Holland': 'NL',
  '荷兰': 'NL',
  'Belgium': 'BE',
  '比利时': 'BE',
  'Luxembourg': 'LU',
  '卢森堡': 'LU',
  'Switzerland': 'CH',
  '瑞士': 'CH',
  'Austria': 'AT',
  '奥地利': 'AT',
  'Norway': 'NO',
  '挪威': 'NO',
  'Sweden': 'SE',
  '瑞典': 'SE',
  'Finland': 'FI',
  '芬兰': 'FI',
  'Denmark': 'DK',
  '丹麦': 'DK',
  'Faroe Islands': 'FO',
  '法罗群岛': 'FO',
  'Iceland': 'IS',
  '冰岛': 'IS',
  'Poland': 'PL',
  '波兰': 'PL',
  'Czech Republic': 'CZ',
  'Czechia': 'CZ',
  '捷克': 'CZ',
  'Slovakia': 'SK',
  '斯洛伐克': 'SK',
  'Hungary': 'HU',
  '匈牙利': 'HU',
  'Romania': 'RO',
  '罗马尼亚': 'RO',
  'Bulgaria': 'BG',
  '保加利亚': 'BG',
  'Croatia': 'HR',
  '克罗地亚': 'HR',
  'Slovenia': 'SI',
  '斯洛文尼亚': 'SI',
  'Serbia': 'RS',
  '塞尔维亚': 'RS',
  'Bosnia and Herzegovina': 'BA',
  'Bosnia': 'BA',
  '波黑': 'BA',
  '波斯尼亚和黑塞哥维那': 'BA',
  'Montenegro': 'ME',
  '黑山': 'ME',
  'North Macedonia': 'MK',
  'Macedonia': 'MK',
  '北马其顿': 'MK',
  'Albania': 'AL',
  '阿尔巴尼亚': 'AL',
  'Kosovo': 'XK',
  '科索沃': 'XK',
  'Ukraine': 'UA',
  '乌克兰': 'UA',
  'Belarus': 'BY',
  '白俄罗斯': 'BY',
  'Moldova': 'MD',
  '摩尔多瓦': 'MD',
  'Lithuania': 'LT',
  '立陶宛': 'LT',
  'Latvia': 'LV',
  '拉脱维亚': 'LV',
  'Estonia': 'EE',
  '爱沙尼亚': 'EE',
  'Russia': 'RU',
  'Russian Federation': 'RU',
  '俄罗斯': 'RU',
  'Malta': 'MT',
  '马耳他': 'MT',
  'Monaco': 'MC',
  '摩纳哥': 'MC',
  'Andorra': 'AD',
  '安道尔': 'AD',
  'San Marino': 'SM',
  '圣马力诺': 'SM',
  'Vatican': 'VA',
  '梵蒂冈': 'VA',
  'Liechtenstein': 'LI',
  '列支敦士登': 'LI',
  'Svalbard': 'NO',
  '斯瓦尔巴': 'NO',

  // ===== Africa =====
  'Egypt': 'EG',
  '埃及': 'EG',
  'Morocco': 'MA',
  '摩洛哥': 'MA',
  'Algeria': 'DZ',
  '阿尔及利亚': 'DZ',
  'Tunisia': 'TN',
  '突尼斯': 'TN',
  'Libya': 'LY',
  '利比亚': 'LY',
  'Sudan': 'SD',
  '苏丹': 'SD',
  'South Sudan': 'SS',
  '南苏丹': 'SS',
  'Ethiopia': 'ET',
  '埃塞俄比亚': 'ET',
  'Eritrea': 'ER',
  '厄立特里亚': 'ER',
  'Djibouti': 'DJ',
  '吉布提': 'DJ',
  'Somalia': 'SO',
  '索马里': 'SO',
  'Kenya': 'KE',
  '肯尼亚': 'KE',
  'Uganda': 'UG',
  '乌干达': 'UG',
  'Tanzania': 'TZ',
  '坦桑尼亚': 'TZ',
  'Rwanda': 'RW',
  '卢旺达': 'RW',
  'Burundi': 'BI',
  '布隆迪': 'BI',
  'Democratic Republic of the Congo': 'CD',
  'DRC': 'CD',
  'Congo': 'CD',
  '刚果民主共和国': 'CD',
  '刚果(金)': 'CD',
  'Republic of the Congo': 'CG',
  '刚果共和国': 'CG',
  '刚果(布)': 'CG',
  'Central African Republic': 'CF',
  '中非': 'CF',
  '中非共和国': 'CF',
  'Cameroon': 'CM',
  '喀麦隆': 'CM',
  'Nigeria': 'NG',
  '尼日利亚': 'NG',
  'Niger': 'NE',
  '尼日尔': 'NE',
  'Chad': 'TD',
  '乍得': 'TD',
  'Mali': 'ML',
  '马里': 'ML',
  'Mauritania': 'MR',
  '毛里塔尼亚': 'MR',
  'Senegal': 'SN',
  '塞内加尔': 'SN',
  'Gambia': 'GM',
  '冈比亚': 'GM',
  'Guinea-Bissau': 'GW',
  '几内亚比绍': 'GW',
  'Guinea': 'GN',
  '几内亚': 'GN',
  'Sierra Leone': 'SL',
  '塞拉利昂': 'SL',
  'Liberia': 'LR',
  '利比里亚': 'LR',
  'Ivory Coast': 'CI',
  "Côte d'Ivoire": 'CI',
  '科特迪瓦': 'CI',
  '象牙海岸': 'CI',
  'Burkina Faso': 'BF',
  '布基纳法索': 'BF',
  'Ghana': 'GH',
  '加纳': 'GH',
  'Togo': 'TG',
  '多哥': 'TG',
  'Benin': 'BJ',
  '贝宁': 'BJ',
  'Gabon': 'GA',
  '加蓬': 'GA',
  'Equatorial Guinea': 'GQ',
  '赤道几内亚': 'GQ',
  'Sao Tome and Principe': 'ST',
  '圣多美和普林西比': 'ST',
  'Angola': 'AO',
  '安哥拉': 'AO',
  'Zambia': 'ZM',
  '赞比亚': 'ZM',
  'Zimbabwe': 'ZW',
  '津巴布韦': 'ZW',
  'Malawi': 'MW',
  '马拉维': 'MW',
  'Mozambique': 'MZ',
  '莫桑比克': 'MZ',
  'Botswana': 'BW',
  '博茨瓦纳': 'BW',
  'Namibia': 'NA',
  '纳米比亚': 'NA',
  'South Africa': 'ZA',
  '南非': 'ZA',
  'Lesotho': 'LS',
  '莱索托': 'LS',
  'Eswatini': 'SZ',
  'Swaziland': 'SZ',
  '斯威士兰': 'SZ',
  '斯威士兰王国': 'SZ',
  'Madagascar': 'MG',
  '马达加斯加': 'MG',
  'Mauritius': 'MU',
  '毛里求斯': 'MU',
  'Seychelles': 'SC',
  '塞舌尔': 'SC',
  'Comoros': 'KM',
  '科摩罗': 'KM',
  'Cape Verde': 'CV',
  '佛得角': 'CV',

  // ===== North America =====
  'USA': 'US',
  'US': 'US',
  'United States': 'US',
  'United States of America': 'US',
  'America': 'US',
  '美国': 'US',
  'Canada': 'CA',
  '加拿大': 'CA',
  'Mexico': 'MX',
  '墨西哥': 'MX',
  'Guatemala': 'GT',
  '危地马拉': 'GT',
  'Belize': 'BZ',
  '伯利兹': 'BZ',
  'Honduras': 'HN',
  '洪都拉斯': 'HN',
  'El Salvador': 'SV',
  '萨尔瓦多': 'SV',
  'Nicaragua': 'NI',
  '尼加拉瓜': 'NI',
  'Costa Rica': 'CR',
  '哥斯达黎加': 'CR',
  'Panama': 'PA',
  '巴拿马': 'PA',
  'Cuba': 'CU',
  '古巴': 'CU',
  'Jamaica': 'JM',
  '牙买加': 'JM',
  'Haiti': 'HT',
  '海地': 'HT',
  'Dominican Republic': 'DO',
  '多米尼加': 'DO',
  'Puerto Rico': 'PR',
  '波多黎各': 'PR',
  'Bahamas': 'BS',
  '巴哈马': 'BS',
  'Trinidad and Tobago': 'TT',
  '特立尼达和多巴哥': 'TT',
  'Barbados': 'BB',
  '巴巴多斯': 'BB',
  'Greenland': 'GL',
  '格陵兰': 'GL',

  // ===== South America =====
  'Brazil': 'BR',
  '巴西': 'BR',
  'Peru': 'PE',
  '秘鲁': 'PE',
  'Argentina': 'AR',
  '阿根廷': 'AR',
  'Chile': 'CL',
  '智利': 'CL',
  'Colombia': 'CO',
  '哥伦比亚': 'CO',
  'Venezuela': 'VE',
  '委内瑞拉': 'VE',
  'Ecuador': 'EC',
  '厄瓜多尔': 'EC',
  'Bolivia': 'BO',
  '玻利维亚': 'BO',
  'Paraguay': 'PY',
  '巴拉圭': 'PY',
  'Uruguay': 'UY',
  '乌拉圭': 'UY',
  'Guyana': 'GY',
  '圭亚那': 'GY',
  'Suriname': 'SR',
  '苏里南': 'SR',
  'French Guiana': 'GF',
  '法属圭亚那': 'GF',

  // ===== Oceania =====
  'Australia': 'AU',
  '澳大利亚': 'AU',
  '澳洲': 'AU',
  'New Zealand': 'NZ',
  '新西兰': 'NZ',
  'Fiji': 'FJ',
  '斐济': 'FJ',
  'Papua New Guinea': 'PG',
  '巴布亚新几内亚': 'PG',
  'Solomon Islands': 'SB',
  '所罗门群岛': 'SB',
  'Vanuatu': 'VU',
  '瓦努阿图': 'VU',
  'New Caledonia': 'NC',
  '新喀里多尼亚': 'NC',
  'French Polynesia': 'PF',
  '法属波利尼西亚': 'PF',
  'Samoa': 'WS',
  '萨摩亚': 'WS',
  'Tonga': 'TO',
  '汤加': 'TO',
  'Palau': 'PW',
  '帕劳': 'PW',
  'Micronesia': 'FM',
  '密克罗尼西亚': 'FM',
  'Marshall Islands': 'MH',
  '马绍尔群岛': 'MH',
  'Guam': 'GU',
  '关岛': 'GU',
  'Kiribati': 'KI',
  '基里巴斯': 'KI',
  'Nauru': 'NR',
  '瑙鲁': 'NR',
  'Tuvalu': 'TV',
  '图瓦卢': 'TV',
}

const normalizeCountryName = (name: string) =>
  name
    .trim()
    .toLowerCase()
    .replace(/[._\-\/]+/g, ' ')
    .replace(/\s+/g, ' ')

export const COUNTRY_NAME_TO_ISO: Record<string, string> = Object.entries(
  RAW_COUNTRY_NAME_TO_ISO
).reduce<Record<string, string>>((acc, [name, iso]) => {
  acc[normalizeCountryName(name)] = iso
  return acc
}, {})

const buildPrimaryNamesByIso = () => {
  const english = new Map<string, string>()
  const chinese = new Map<string, string>()
  const englishAliases = new Map<string, Set<string>>()

  for (const [name, iso] of Object.entries(RAW_COUNTRY_NAME_TO_ISO)) {
    if (!english.has(iso) && /[A-Za-z]/.test(name)) {
      english.set(iso, name)
    }
    if (!chinese.has(iso) && /[\u4e00-\u9fff]/.test(name)) {
      chinese.set(iso, name)
    }
    if (/[A-Za-z]/.test(name)) {
      const set = englishAliases.get(iso) || new Set<string>()
      set.add(name)
      englishAliases.set(iso, set)
    }
  }

  return { english, chinese, englishAliases }
}

const PRIMARY_NAMES_BY_ISO = buildPrimaryNamesByIso()

export function getCountryISOCode(countryName: string): string | null {
  if (!countryName) return null
  const key = normalizeCountryName(countryName)
  return COUNTRY_NAME_TO_ISO[key] ?? null
}

export function getPrimaryCountryNameEn(isoCode: string): string | null {
  if (!isoCode) return null
  return PRIMARY_NAMES_BY_ISO.english.get(isoCode.toUpperCase()) ?? null
}

export function getPrimaryCountryNameZh(isoCode: string): string | null {
  if (!isoCode) return null
  return PRIMARY_NAMES_BY_ISO.chinese.get(isoCode.toUpperCase()) ?? null
}

export function getCountryAliasNamesEn(isoCode: string): string[] {
  if (!isoCode) return []
  const set = PRIMARY_NAMES_BY_ISO.englishAliases.get(isoCode.toUpperCase())
  return set ? Array.from(set.values()) : []
}
