export interface Location {
  country: string
  countryZh: string  // 中文国家名
  city: string
  landmark: string
  landmarkZh: string  // 中文地标名
  timezone: string  // 时区标识
  landscapeUrl: string
}

export const LOCATIONS: Location[] = [
  // 亚洲 (UTC+5 ~ UTC+9)
  {
    country: 'Japan',
    countryZh: '日本',
    city: 'Kyoto',
    landmark: 'Fushimi Inari Shrine',
    landmarkZh: '伏见稻荷大社',
    timezone: 'Asia/Tokyo',
    landscapeUrl: 'https://images.unsplash.com/photo-1478436127897-769e1b3f0f36',
  },
  {
    country: 'Japan',
    countryZh: '日本',
    city: 'Osaka',
    landmark: 'Dotonbori',
    landmarkZh: '道顿堀',
    timezone: 'Asia/Tokyo',
    landscapeUrl: 'https://images.unsplash.com/photo-1590559899731-a382839e5549',
  },
  {
    country: 'South Korea',
    countryZh: '韩国',
    city: 'Seoul',
    landmark: 'Gyeongbokgung Palace',
    landmarkZh: '景福宫',
    timezone: 'Asia/Seoul',
    landscapeUrl: 'https://images.unsplash.com/photo-1534274988757-a28bf1a57c17',
  },
  {
    country: 'China',
    countryZh: '中国',
    city: 'Shanghai',
    landmark: 'The Bund',
    landmarkZh: '外滩',
    timezone: 'Asia/Shanghai',
    landscapeUrl: 'https://images.unsplash.com/photo-1537531383496-f4749b918caa',
  },
  {
    country: 'China',
    countryZh: '中国',
    city: 'Guilin',
    landmark: 'Li River',
    landmarkZh: '漓江',
    timezone: 'Asia/Shanghai',
    landscapeUrl: 'https://images.unsplash.com/photo-1529921879218-f99546d03a50',
  },
  {
    country: 'Thailand',
    countryZh: '泰国',
    city: 'Bangkok',
    landmark: 'Grand Palace',
    landmarkZh: '大皇宫',
    timezone: 'Asia/Bangkok',
    landscapeUrl: 'https://images.unsplash.com/photo-1563492065599-3520f775eeed',
  },
  {
    country: 'Vietnam',
    countryZh: '越南',
    city: 'Ha Long Bay',
    landmark: 'Ha Long Bay',
    landmarkZh: '下龙湾',
    timezone: 'Asia/Ho_Chi_Minh',
    landscapeUrl: 'https://images.unsplash.com/photo-1528127269322-539801943592',
  },
  {
    country: 'India',
    countryZh: '印度',
    city: 'Agra',
    landmark: 'Taj Mahal',
    landmarkZh: '泰姬陵',
    timezone: 'Asia/Kolkata',
    landscapeUrl: 'https://images.unsplash.com/photo-1564507592333-c60657eea523',
  },
  {
    country: 'Singapore',
    countryZh: '新加坡',
    city: 'Singapore',
    landmark: 'Marina Bay Sands',
    landmarkZh: '滨海湾金沙',
    timezone: 'Asia/Singapore',
    landscapeUrl: 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd',
  },
  {
    country: 'Indonesia',
    countryZh: '印度尼西亚',
    city: 'Bali',
    landmark: 'Tanah Lot Temple',
    landmarkZh: '海神庙',
    timezone: 'Asia/Jakarta',
    landscapeUrl: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4',
  },
  {
    country: 'Nepal',
    countryZh: '尼泊尔',
    city: 'Kathmandu',
    landmark: 'Himalaya Mountains',
    landmarkZh: '喜马拉雅山',
    timezone: 'Asia/Kathmandu',
    landscapeUrl: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa',
  },
  {
    country: 'UAE',
    countryZh: '阿联酋',
    city: 'Dubai',
    landmark: 'Burj Khalifa',
    landmarkZh: '哈利法塔',
    timezone: 'Asia/Dubai',
    landscapeUrl: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c',
  },

  // 欧洲 (UTC+0 ~ UTC+3)
  {
    country: 'UK',
    countryZh: '英国',
    city: 'London',
    landmark: 'Big Ben',
    landmarkZh: '大本钟',
    timezone: 'Europe/London',
    landscapeUrl: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad',
  },
  {
    country: 'France',
    countryZh: '法国',
    city: 'Provence',
    landmark: 'Lavender Fields',
    landmarkZh: '薰衣草田',
    timezone: 'Europe/Paris',
    landscapeUrl: 'https://images.unsplash.com/photo-1499002238440-d264edd596ec',
  },
  {
    country: 'Italy',
    countryZh: '意大利',
    city: 'Venice',
    landmark: 'Grand Canal',
    landmarkZh: '大运河',
    timezone: 'Europe/Rome',
    landscapeUrl: 'https://images.unsplash.com/photo-1514890547357-a9ee288728e0',
  },
  {
    country: 'Italy',
    countryZh: '意大利',
    city: 'Rome',
    landmark: 'Colosseum',
    landmarkZh: '罗马斗兽场',
    timezone: 'Europe/Rome',
    landscapeUrl: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5',
  },
  {
    country: 'Spain',
    countryZh: '西班牙',
    city: 'Barcelona',
    landmark: 'Sagrada Familia',
    landmarkZh: '圣家堂',
    timezone: 'Europe/Madrid',
    landscapeUrl: 'https://images.unsplash.com/photo-1583422409516-2895a77efded',
  },
  {
    country: 'Greece',
    countryZh: '希腊',
    city: 'Santorini',
    landmark: 'Oia Village',
    landmarkZh: '伊亚小镇',
    timezone: 'Europe/Athens',
    landscapeUrl: 'https://images.unsplash.com/photo-1613395877344-13d4a8e0d49e',
  },
  {
    country: 'Netherlands',
    countryZh: '荷兰',
    city: 'Amsterdam',
    landmark: 'Canal Ring',
    landmarkZh: '运河环',
    timezone: 'Europe/Amsterdam',
    landscapeUrl: 'https://images.unsplash.com/photo-1534351590666-13e3e96b5017',
  },
  {
    country: 'Switzerland',
    countryZh: '瑞士',
    city: 'Interlaken',
    landmark: 'Swiss Alps',
    landmarkZh: '阿尔卑斯山',
    timezone: 'Europe/Zurich',
    landscapeUrl: 'https://images.unsplash.com/photo-1531366936337-7c912a4589a7',
  },
  {
    country: 'Norway',
    countryZh: '挪威',
    city: 'Tromsø',
    landmark: 'Northern Lights',
    landmarkZh: '北极光',
    timezone: 'Europe/Oslo',
    landscapeUrl: 'https://images.unsplash.com/photo-1483347756197-71ef80e95f73',
  },
  {
    country: 'Iceland',
    countryZh: '冰岛',
    city: 'Reykjavik',
    landmark: 'Blue Lagoon',
    landmarkZh: '蓝湖温泉',
    timezone: 'Atlantic/Reykjavik',
    landscapeUrl: 'https://images.unsplash.com/photo-1504829857797-ddff29c27927',
  },
  {
    country: 'Turkey',
    countryZh: '土耳其',
    city: 'Cappadocia',
    landmark: 'Hot Air Balloons',
    landmarkZh: '热气球',
    timezone: 'Europe/Istanbul',
    landscapeUrl: 'https://images.unsplash.com/photo-1641128324972-af3212f0f6bd',
  },
  {
    country: 'Russia',
    countryZh: '俄罗斯',
    city: 'Moscow',
    landmark: 'Red Square',
    landmarkZh: '红场',
    timezone: 'Europe/Moscow',
    landscapeUrl: 'https://images.unsplash.com/photo-1513326738677-b964603b136d',
  },

  // 非洲 (UTC+0 ~ UTC+3)
  {
    country: 'Egypt',
    countryZh: '埃及',
    city: 'Giza',
    landmark: 'Pyramids of Giza',
    landmarkZh: '吉萨金字塔',
    timezone: 'Africa/Cairo',
    landscapeUrl: 'https://images.unsplash.com/photo-1503177119275-0aa32b3a9368',
  },
  {
    country: 'Morocco',
    countryZh: '摩洛哥',
    city: 'Marrakech',
    landmark: 'Jardin Majorelle',
    landmarkZh: '马约尔花园',
    timezone: 'Africa/Casablanca',
    landscapeUrl: 'https://images.unsplash.com/photo-1489749798305-4fea3ae63d43',
  },
  {
    country: 'South Africa',
    countryZh: '南非',
    city: 'Cape Town',
    landmark: 'Table Mountain',
    landmarkZh: '桌山',
    timezone: 'Africa/Johannesburg',
    landscapeUrl: 'https://images.unsplash.com/photo-1580060839134-75a5edca2e99',
  },
  {
    country: 'Kenya',
    countryZh: '肯尼亚',
    city: 'Masai Mara',
    landmark: 'Safari Savanna',
    landmarkZh: '马赛马拉草原',
    timezone: 'Africa/Nairobi',
    landscapeUrl: 'https://images.unsplash.com/photo-1547970810-dc1eac37d174',
  },

  // 北美洲 (UTC-5 ~ UTC-8)
  {
    country: 'USA',
    countryZh: '美国',
    city: 'New York',
    landmark: 'Times Square',
    landmarkZh: '时代广场',
    timezone: 'America/New_York',
    landscapeUrl: 'https://images.unsplash.com/photo-1534430480872-3498386e7856',
  },
  {
    country: 'USA',
    countryZh: '美国',
    city: 'San Francisco',
    landmark: 'Golden Gate Bridge',
    landmarkZh: '金门大桥',
    timezone: 'America/Los_Angeles',
    landscapeUrl: 'https://images.unsplash.com/photo-1449034446853-66c86144b0ad',
  },
  {
    country: 'USA',
    countryZh: '美国',
    city: 'Las Vegas',
    landmark: 'The Strip',
    landmarkZh: '拉斯维加斯大道',
    timezone: 'America/Los_Angeles',
    landscapeUrl: 'https://images.unsplash.com/photo-1605833556294-ea5c7a74f57d',
  },
  {
    country: 'USA',
    countryZh: '美国',
    city: 'Arizona',
    landmark: 'Grand Canyon',
    landmarkZh: '大峡谷',
    timezone: 'America/Phoenix',
    landscapeUrl: 'https://images.unsplash.com/photo-1474044159687-1ee9f3a51722',
  },
  {
    country: 'Canada',
    countryZh: '加拿大',
    city: 'Banff',
    landmark: 'Lake Louise',
    landmarkZh: '路易斯湖',
    timezone: 'America/Edmonton',
    landscapeUrl: 'https://images.unsplash.com/photo-1502085671122-2d218cd434e6',
  },
  {
    country: 'Canada',
    countryZh: '加拿大',
    city: 'Niagara Falls',
    landmark: 'Niagara Falls',
    landmarkZh: '尼亚加拉瀑布',
    timezone: 'America/Toronto',
    landscapeUrl: 'https://images.unsplash.com/photo-1489447068241-b3490214e879',
  },
  {
    country: 'Mexico',
    countryZh: '墨西哥',
    city: 'Cancun',
    landmark: 'Chichen Itza',
    landmarkZh: '奇琴伊察',
    timezone: 'America/Cancun',
    landscapeUrl: 'https://images.unsplash.com/photo-1518638150340-f706e86654de',
  },

  // 南美洲 (UTC-3 ~ UTC-5)
  {
    country: 'Brazil',
    countryZh: '巴西',
    city: 'Rio de Janeiro',
    landmark: 'Christ the Redeemer',
    landmarkZh: '基督救世主像',
    timezone: 'America/Sao_Paulo',
    landscapeUrl: 'https://images.unsplash.com/photo-1483729558449-99ef09a8c325',
  },
  {
    country: 'Peru',
    countryZh: '秘鲁',
    city: 'Cusco',
    landmark: 'Machu Picchu',
    landmarkZh: '马丘比丘',
    timezone: 'America/Lima',
    landscapeUrl: 'https://images.unsplash.com/photo-1526392060635-9d6019884377',
  },
  {
    country: 'Argentina',
    countryZh: '阿根廷',
    city: 'Patagonia',
    landmark: 'Perito Moreno Glacier',
    landmarkZh: '莫雷诺冰川',
    timezone: 'America/Argentina/Buenos_Aires',
    landscapeUrl: 'https://images.unsplash.com/photo-1551279880-03041531948f',
  },
  {
    country: 'Chile',
    countryZh: '智利',
    city: 'Atacama',
    landmark: 'Atacama Desert',
    landmarkZh: '阿塔卡马沙漠',
    timezone: 'America/Santiago',
    landscapeUrl: 'https://images.unsplash.com/photo-1489392191049-fc10c97e64b6',
  },

  // 大洋洲 (UTC+10 ~ UTC+12)
  {
    country: 'Australia',
    countryZh: '澳大利亚',
    city: 'Sydney',
    landmark: 'Sydney Opera House',
    landmarkZh: '悉尼歌剧院',
    timezone: 'Australia/Sydney',
    landscapeUrl: 'https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9',
  },
  {
    country: 'Australia',
    countryZh: '澳大利亚',
    city: 'Queensland',
    landmark: 'Great Barrier Reef',
    landmarkZh: '大堡礁',
    timezone: 'Australia/Brisbane',
    landscapeUrl: 'https://images.unsplash.com/photo-1559128010-7c1ad6e1b6a5',
  },
  {
    country: 'New Zealand',
    countryZh: '新西兰',
    city: 'Queenstown',
    landmark: 'Milford Sound',
    landmarkZh: '米尔福德峡湾',
    timezone: 'Pacific/Auckland',
    landscapeUrl: 'https://images.unsplash.com/photo-1507699622108-4be3abd695ad',
  },
  {
    country: 'New Zealand',
    countryZh: '新西兰',
    city: 'Matamata',
    landmark: 'Hobbiton',
    landmarkZh: '霍比屯',
    timezone: 'Pacific/Auckland',
    landscapeUrl: 'https://images.unsplash.com/photo-1507097634215-e82e6b552cae',
  },
  {
    country: 'Fiji',
    countryZh: '斐济',
    city: 'Nadi',
    landmark: 'Fiji Islands',
    landmarkZh: '斐济群岛',
    timezone: 'Pacific/Fiji',
    landscapeUrl: 'https://images.unsplash.com/photo-1589179899031-d86b7e3fcd61',
  },
]
